/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CalculatorAppRouteImport } from './routes/calculator-app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramLeadRouteImport } from './routes/api/public/telegram-lead'

const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorAppRoute = CalculatorAppRouteImport.update({
  id: '/calculator-app',
  path: '/calculator-app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramLeadRoute = ApiPublicTelegramLeadRouteImport.update({
  id: '/api/public/telegram-lead',
  path: '/api/public/telegram-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator-app': typeof CalculatorAppRoute
  '/privacy': typeof PrivacyRoute
  '/roi': typeof RoiRoute
  '/api/public/telegram-lead': typeof ApiPublicTelegramLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator-app': typeof CalculatorAppRoute
  '/privacy': typeof PrivacyRoute
  '/roi': typeof RoiRoute
  '/api/public/telegram-lead': typeof ApiPublicTelegramLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator-app': typeof CalculatorAppRoute
  '/privacy': typeof PrivacyRoute
  '/roi': typeof RoiRoute
  '/api/public/telegram-lead': typeof ApiPublicTelegramLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator-app'
    | '/privacy'
    | '/roi'
    | '/api/public/telegram-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator-app'
    | '/privacy'
    | '/roi'
    | '/api/public/telegram-lead'
  id:
    | '__root__'
    | '/'
    | '/calculator-app'
    | '/privacy'
    | '/roi'
    | '/api/public/telegram-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorAppRoute: typeof CalculatorAppRoute
  PrivacyRoute: typeof PrivacyRoute
  RoiRoute: typeof RoiRoute
  ApiPublicTelegramLeadRoute: typeof ApiPublicTelegramLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator-app': {
      id: '/calculator-app'
      path: '/calculator-app'
      fullPath: '/calculator-app'
      preLoaderRoute: typeof CalculatorAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-lead': {
      id: '/api/public/telegram-lead'
      path: '/api/public/telegram-lead'
      fullPath: '/api/public/telegram-lead'
      preLoaderRoute: typeof ApiPublicTelegramLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorAppRoute: CalculatorAppRoute,
  PrivacyRoute: PrivacyRoute,
  RoiRoute: RoiRoute,
  ApiPublicTelegramLeadRoute: ApiPublicTelegramLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
